### ISSUE TITLE
Read TinyDSOD using OpenCV

### ISSUE THREAD

**Issue by didulle** [lyxok1/Tiny-DSOD#15]
Hello,
OpenCV allows to read/process DNN models using cv::dnn::readNetFromCaffe. However some layers are not implemented yet in particular "Upsample" and "conv_dw" layers. Leading to the following error during the forward pass since those layers are not implemented

Error: Unspecified error (Can't create layer "Upsample1" of type "Upsample") in cv::dnn::LayerData::getLayerInstance, file \opencv\modules\dnn\src\dnn.cpp, line 518

Does anyone have managed to add those layers to the DNN modules of OPENCV?

Thanks !!!

**Comment by richipower** [comment]
Hello @didulle i just got the pretrained models and i see the error that you encountered, did you manage to create the missing Layers in OpenCV?

**Comment by didulle** [comment]
Yes by implementing the Upsample Layer using the following tutorial: https://docs.opencv.org/4.0.0/dc/db1/tutorial_dnn_custom_layers.html

**Comment by kevkid** [comment]
> Yes by implementing the Upsample Layer using the following tutorial: https://docs.opencv.org/4.0.0/dc/db1/tutorial_dnn_custom_layers.html

Could you share this? I am currently trying to program this in python and am a little stuck.

@lyxok1 Could you give some insight on this? How should we implement this layer in python for this use?
