### ISSUE TITLE
Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: ConvolutionDepthwise

### ISSUE THREAD

**Issue by didulle** [lyxok1/Tiny-DSOD#2]
Hi,

When I try to run the solver to perform the training, Caffe didn't recognize "ConvolutionDepthwise" layer type.

Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: ConvolutionDepthwise

Thanks

**Comment by lyxok1** [comment]
Hi, please make sure you are compiling and using our revised caffe version, since the convolution depth-wise and upsample layers are not supported by official version.

**Comment by didulle** [comment]
Thanks !!! I have added those layers to the official version and it works
